### ISSUE TITLE
Its possible to add more features?

### ISSUE THREAD

**Issue by hectorevil** [tommaier123/XBatteryStatus#18] opened 2023-09-15 18:17 UTC
Like other  projects like 

https://github.com/NiyaShy/XB1ControllerBatteryIndicator

 - Show on tray icon when battery its full and chargin.
 - Possibility to ad new sounds

**Comment by tommaier123** [comment] 2023-09-15 18:23
- It would be possible to show if a controller is connected via USB but I don't think there is a way to get the battery level or even if it is charging.
- The sounds is not controlled by the app, tis the windows notification sound.

**Comment by tommaier123** [comment] 2023-09-23 22:55
Duplicate of #6

**Closed by tommaier123** 2023-09-23 22:55 UTC
